### ISSUE TITLE
Create an "RFC" process

### ISSUE THREAD

**Issue by griwes** [reaver-project/vapor#17]
This is a bit cute at this stage, but I want to have a process for how this is supposed to work that I'll mostly follow. This will also force me to try to actually write a proper specification of the language and of the library for things that I've already done and for things I'm doing, *before* actually diving into full implementation mode (although those two processes should probably go together).

There's a bunch of open questions I'll need to answer myself:
* [ ] do I keep the specs in the same repository as the compiler?
* [ ] do I require separate pull requests for changes in the spec and in the implementation, or a single one? On one hand, having a single PR would simplify the management of this, but on the other hand, in case someone wants to review just the spec changes, it could be bothersome to sift through the implementation changes too. However, if I want to move to having the changes to different parts of the compiler split between multiple PRs (which is probably a good idea), then this'd also need to be separate.
* [ ] Markdown?
* [ ] how do I triage the RFCs and decide the priorities? So far this is a deeply unimportant question, but it'll need answering _if_ I ever get RFCs from other people.
